apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossview-role
rules:
# Core API resources - read access
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - services
    - configmaps
    - secrets
    - events
    - nodes
    - persistentvolumes
    - persistentvolumeclaims
  verbs: ["get", "list", "watch"]
# Custom resources - read access
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs: ["get", "list", "watch"]
# All other API groups - read access (for Crossplane, etc.)
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

