# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: operation-examples
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/scott4dev/crossplane-playground
#     path: operations
#     targetRevision: HEAD
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: default
#   syncPolicy:
#     automated:
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
# ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/scott4dev/crossplane-box
    path: yaml
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-crossview
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/scott4dev/crossplane-box
    path: crossview
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: example-with-crossplane
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/scott4dev/crossplane-box
#     path: crossplane-example
#     targetRevision: HEAD
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: default
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
# ---