apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-operations
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: crossplane-operations
    repoURL: https://github.com/scott4dev/crossplane-playground
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---